version: '3.8'

services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: unless-stopped
    ports:
      - "3000:8080"  # Expose port 8080 inside the container to port 3000 on the host
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    environment:
      - TZ=America/Toronto
    networks:
      - glance_network

networks:
  glance_network:
    driver: bridge
